# -*- coding: utf-8 -*-
"""python.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fL91Y3H2scAbc1jRfw_--jEMStG4YU37
"""

import streamlit as st
import pandas as pd
import pickle

# Load the trained model
filename = 'linear_regression_model.pkl'
loaded_model = pickle.load(open(filename, 'rb'))

st.title('Exam Score Predictor')
st.write('Enter study and sleep hours to predict exam score.')

# Input widgets for study_hours and sleep_hours
# Using the observed min/max from the training data for reasonable slider ranges
study_hours = st.slider('Study Hours', min_value=0.0, max_value=12.0, value=X['study_hours'].mean(), step=0.1)
sleep_hours = st.slider('Sleep Hours', min_value=3.0, max_value=10.0, value=X['sleep_hours'].mean(), step=0.1)

# Make prediction
if st.button('Predict Exam Score'):
    prediction_input = pd.DataFrame([[study_hours, sleep_hours]], columns=['study_hours', 'sleep_hours'])
    predicted_score = loaded_model.predict(prediction_input)[0]
    st.success(f'Predicted Exam Score: {predicted_score:.2f}')

# To run this Streamlit app in Colab, you would typically save this code to a file (e.g., app.py)
# and then use ngrok or a similar service to expose it. For demonstration purposes, you can
# copy this code block into a local app.py file and run `streamlit run app.py` in your terminal.