# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y10DZRCSQy_lyr-KuvvnSWL4qlB_wTjl
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import matplotlib.pyplot as plt
data = pd.read_csv("/content/study_time_vs_marks_dataset.csv")
X = data[['study_hours', 'sleep_hours']]
y = data['exam_score']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))
print("\nModel Equation:")
print(f"exam_score = {model.coef_[0]:.2f} * study_hours + {model.coef_[1]:.2f} * sleep_hours + {model.intercept_:.2f}")
study = float(input("Enter study hours: "))
sleep = float(input("Enter sleep hours: "))
prediction = model.predict([[study, sleep]])
print("Predicted Exam Score:", prediction[0])
plt.scatter(X_test['study_hours'], y_test, color='blue', label='Actual')
plt.scatter(X_test['study_hours'], y_pred, color='red', label='Predicted')
plt.xlabel("Study Hours")
plt.ylabel("Exam Score")
plt.legend()
plt.title("Study Hours vs Exam Score")
plt.show()

import pickle

# Save the trained model
filename = 'linear_regression_model.pkl'
pickle.dump(model, open(filename, 'wb'))
print(f"Model saved as {filename}")

"""Next, I'll create the Streamlit application code. You'll need to install `streamlit` to run this app. After running the cell below, you can save its content to a Python file (e.g., `app.py`) and run it from your terminal using `streamlit run app.py`."""

import streamlit as st
import pandas as pd
import pickle

# Load the trained model
filename = 'linear_regression_model.pkl'
loaded_model = pickle.load(open(filename, 'rb'))

st.title('Exam Score Predictor')
st.write('Enter study and sleep hours to predict exam score.')

# Input widgets for study_hours and sleep_hours
# Using the observed min/max from the training data for reasonable slider ranges
study_hours = st.slider('Study Hours', min_value=0.0, max_value=12.0, value=X['study_hours'].mean(), step=0.1)
sleep_hours = st.slider('Sleep Hours', min_value=3.0, max_value=10.0, value=X['sleep_hours'].mean(), step=0.1)

# Make prediction
if st.button('Predict Exam Score'):
    prediction_input = pd.DataFrame([[study_hours, sleep_hours]], columns=['study_hours', 'sleep_hours'])
    predicted_score = loaded_model.predict(prediction_input)[0]
    st.success(f'Predicted Exam Score: {predicted_score:.2f}')

# To run this Streamlit app in Colab, you would typically save this code to a file (e.g., app.py)
# and then use ngrok or a similar service to expose it. For demonstration purposes, you can
# copy this code block into a local app.py file and run `streamlit run app.py` in your terminal.